### ISSUE TITLE
Placement Pieces 

### ISSUE THREAD

**Issue by burtomic** [cs361w2019-osu/sprint1-project-group-12#10]
This issue deals with implementing a better user interface for placing the pieces. The pieces buttons will be faded once that specific piece has been place and the button will lose functionality. The buttons will disappear once all pieces have been placed.

**Comment by zunyueseattle** [comment]
this issue works on how to tracking information after game begin. information should shows on board to let user know how many times he miss, hit, and sunk.

**Comment by burtomic** [comment]
This issue has been implemented in the placement branch.
